const listPercent = [
    {
        title: "100% DE DESCUENTO",
        list: [
            "Consulta de Urgencia",
            "Consulta odontología general",
            "Limpieza dental + fluor (anual)",
        ],
    },
    {
        title: "80% DE DESCUENTO",
        list: [
            "Sutura"
        ],
    },
    {
        title: "60% DE DESCUENTO",
        list: [
            "Amalgama (1 superficie)",
            "Amalgama (2 superficies)",
            "Amalgama (3 o más superficies)",
            "Blanqueamiento dental completo",
        ],
    },
    {
        title: "55% DE DESCUENTO",
        list: ["Resina compuesta"],
    },
    {
        title: "50% DE DESCUENTO",
        list: [
            "Ajuste oclusal",
            "Amalgama compuesta",
            "Amalga pin",
            "Base cavitaria Dycal",
            "Base cavitaria fotocurable",
            "Base cavitaria ionómero",
            "Blanqueamiento (1 diente)",
            "Carillas de resina",
            "Emergencia",
            "Incrustación de resina",
            "Montaje en marco radiográfico",
            "Profilaxis con Prophymate",
            "Pulido de amalgama",
            "Reconstrucción con resina",
            "Reconstrucción estética con resina",
            "Remoción de manchas con AIR FLOW",
            "Tratamiento temporal base",
        ],
    },
    /*{
        title: "40% DE DESCUENTO",
        list: [
            "Frenoctomía",
            "Modelos de yeso (c / u)",
            "Raspado y alisado",
            "Tratamiento de ortodoncia",
        ],
    },*/
    {
        title: "30% DE DESCUENTO",
        list: [
            "Ameloplastia resina",
            "Ameloplastia sellante",
            "Aparato de ortodoncia",
            "Apexificación",
            "Apicectomía anterior",
            "Apicectomía molar",
            "Apicectomía premolar",
            "Caja plástica para retenedor",
            "Cambio de liga",
            "Colocación de freno superior - inferior",
            "Consulta de ortodoncia ",
            "Consultas especializadas",
            "Control de aparato fijo - removible en niños",
            "Control de movimiento fijo",
            "Control de movimiento removible",
            "Control de Ortodoncia",
            "Control de prótesis",
            "Control de pulpotomía",
            "Endodoncia anterior",
            "Endodoncia molar",
            "Endodoncia premolar",
            "Extracción deciduo (anterior o posterior)",
            "Frenectomía",
            "Juego Radiográfico",
            "Modelos de Yeso",
            "Montaje de marco radiográfico",
            "Pulpectomía",
            "Pulpotomía",
            "Raspado y alisado",
            "Recontorneo estético de dientes anteriores (c / u)",
            "Re - endodoncia anterior",
            "Re - endodoncia molar",
            "Re - endodoncia premolar",
            "Remoción de aparatología",
            "Remoción de bracket (1 arcada)",
            "Remoción de bracket parcial",
            "Remoción de bracket superior e inferior",
            "Retenedor fijo",
            "Retenedor removible Hawlay",
            "Sellante fisura adulto",
            "Sellantes",
            "Tratamiento de ortodoncia (1 arcada)",
        ],
    },
    {
        title: "25% DE DESCUENTO",
        list: [
            "Cementación de banda",
            "Consulta Odontología General",
            "Consulta Odontopediatría",
            "Drenaje de absceso",
            "Perdida de arco",
            "Profilaxis infantil",
            "Prótesis removible (superior o inferior)",
            "Radiografía Cefalométrica",
            "Radiografía Panorámica",
            "Radiografía Periapical",
        ],
    },
    {
        title: "20% DE DESCUENTO",
        list: [
            "Alargamiento de corona",
            "Aleta Maryland",
            "Amputación radicular",
            "Biopsia (laboratorio)",
            "Carilla de porcelana",
            "Cementación aparato - corona",
            "Cirugía aérea edéntula",
            "Cirugía de torus lingual (por cuadrante)",
            "Cirugía estética periodontal",
            "Cirugía exploratoria",
            "Cirugía mucogingival",
            "Cirugía ósea(resección y remod ",
            "CL Resina (1 superficie)",
            "CL Resina (2 superficie)",
            "CL Resina (3 superficie).",
            "CL Resina (4 o más superficies)",
            "Colocación de Brackets de cerámica",
            "Colocación de Brackets de porcelana",
            "Colocación de Brackets Zafiro",
            "Control de férula",
            "Corona cerómeno",
            "Corona completa en metal (acero inoxidable)",
            "Corona de porcelana pura",
            "Corona metal porcelana",
            "Corona sobre implantes",
            "Corona temporal",
            "Exodoncia compleja",
            "Exodoncia diente incluido",
            "Exodoncia semi-compleja",
            "Exodoncia simple",
            "Exodoncia 3ra.molar erupcionada",
            "Exodoncia 3ra.molar incluida",
            "Exodoncia 3ra.molar retenida",
            "Exodoncia 3ra.molar semi incluida",
            "Férula",
            "Gingivectomía (cada diente)",
            "Gingivectomía (por cuadrante)",
            "Hemisección",
            "Implantes",
            "Injerto gingival libre",
            "Injerto óseo",
            "Jaula",
            "Mantenedor con espacio bilateral",
            "Mantenedor con espacio unilateral",
            "Mantenedor con frente removoble estético",
            "Mantenimiento periodontal",
            "Mucocele y ránula",
            "Muñón",
            "Pernos (cada uno)",
            "Placas oclusales",
            "Procedimiento de cuña distal",
            "Procedimiento por colgajo periodontico",
            "Prótesis asistencial",
            "Prótesis parcial flex",
            "Prótesis total (superior o inferior)",
            "Prótesis Valplast",
            "Provisionales (por unidad)",
            "Rebase",
            "Reparacion en consultorio",
            "Reparacion en laboratorio",
            "Reparación ósea guiada",
            "Splint",
            "Tornillo de cicatrización",
            "Tratamiento paliativo",
            "Tratamiento de ortodoncia de contado",
            "Ventana para exploración de diente",
            "Ventana quirúrgica en niños",
        ],
    },
];

export default listPercent;
