const listPercentPrevencion = [
    {
        title: "75% MEDICINA GENERAL",
        list: [
		    "*Consulta de Medicina General (Costo fijo 5.00)",
        ],
    },
    {
        title: "10% MEDICINA PREVENTIVA",
        list: [
            "*Consulta de Especialidades",
            "Cardiología",
            "Neumología",
			"Neurofisiología",
			"Pediatría",
			"Otorrinolaringología",
			"Nutrición",
			"Cirugía General",
			"Oftalmología",
			"Medicina Interna",
            "Cirugía Vascular",
            "Hematología Pediátrica",
            "Psicología",
            "Ortopedia",
            "Geriatría",
            "Ginecología",
            "Urología",
        ],
    },
    {
        title: "25% EXÁMENES ESPECIALIZADOS/IMÁGENES",
        list: [
            "Resonancia Magnética",
			"Tomografías",
			"Ultrasonidos",
			"Todo tipo de Rayos X",
			"Estudios Odontológicos Avanzados",
			"Tomografía Dental",
			"Fotografías Intraorales",
			"Fotografías extraorales",
			"Radiografías Cefalométricas",
			"Radiografías Panorámicas",
			"Radiografías Periapicales",
        ],
    },
    {
        title: "25% TODO TIPO DE LABORATORIO CLÍNICO",
        list: [
            "Hematología",
            "Química en General",
            "Química Especial y Hormonas",
            "Pruebas Infecciosas",
			"Serología General",
			"Biología Molecular",
			"Urinálisis",
			"Parasitología General",
			"Microbiología",
			"Patología y Citología",
        ],
    },
    {
        title: "CLÍNICAS Y LABORATORIOS DE LA RED",
        list: [
            "Clinilab Calle 50",
            "Clinilab El Dorado",
            "Clinilab Santa Maria Plaza",
            "Clinilab Costa Verde",
            "Clinilab Penonomé",
        ],
    },
    {
        title: "PERFILES DISPONIBLES EN LA CLÍNICA",
        list: [
            "Perfil Hepático",
            "Perfil Renal",
            "Perfil Autoinmune",
            "Perfil Cardiovascular",
			"Perfil Marcadores Tumorales",
			"Perfil Hormonal Mujer",
			"Perfil Hormonal Hombre",
			"Perfil Sindrome Metabólico",
			"Perfil Lipídico",
			"Perfil Tiroideo",
			"Perfil Anemia",
			"Perfil Gastrico",
			"Perfil Celiaco",
			"Perfil Alergias",
        ],
    },
    {
        title: "CENTRO ESPECIALIZADO DE IMÁGENES",
        list: [
            "Radimagen Vía Israel",
            "Clinilab de Penonomé",
        ],
    },
];

export default listPercentPrevencion;
